baseURL = "https://vahurtad.github.io/"
canonifyURLs = true
languageCode = "en-us"
title = "My New Hugo Site"
contentdir = "content/post"
layoutdir = "layouts"
publishdir = "public"
canonifyurls = true
